### ISSUE TITLE
[BUG] `TypeError: issubclass() arg 1 must be a class when using llm.generate() wih structured output

### ISSUE THREAD

**Issue by javimosa** [argilla-io/distilabel#1010]
**Describe the bug**
I'm trying to use the structured data generation feature in order to create a function calling dataset. Unfortunately, when using the code provided by the docs I'm getting a `TypeError: issubclass() arg 1 must be a class`. Sorry if it's pretty obvious, I'm new to the framework. I'm using this docs as reference: [docs](https://distilabel.argilla.io/1.3.2/sections/how_to_guides/advanced/structured_generation/#instructor) 

I suspect this may be related to how `structured_output={"schema": User}` is handled. Apologies if it's obvious, I'm new to the framework.

**To Reproduce**
1. Use the following code snippet:

```python
import json
from distilabel.llms import OpenAILLM
from pydantic import BaseModel

class User(BaseModel):
    name: str
    last_name: str
    id: int

llm = OpenAILLM(
    model="gpt-4o",
    structured_output={"schema": User},
    api_key="..."
)
llm.load()

result = llm.generate(
    [[{"role": "user", "content": "Create a user profile for the following marathon"}]],
    max_new_tokens=256
)

data = json.loads(result[0][0])
```
**Output**
[logs.txt](https://github.com/user-attachments/files/17228123/logs.txt)

**Expected behaviour**
The expected behaviour should be obtaining a JSON such as: {'name': 'John', 'last_name': 'Doe', 'id': 12345}

**Desktop:**
 - Package version: 1.3.2
 - Python version: 3.10.12
 - Pydantic version: 2.9.2
 - OS: WSL

**Comment by plaguss** [comment]
Hi @javimosa, could yo try installing from `develop`? There was a bug in how we handled the structured output. From develop I have the following:

```python
import json
from distilabel.llms import OpenAILLM
from pydantic import BaseModel

class User(BaseModel):
    name: str
    last_name: str
    id: int

llm = OpenAILLM(
    model="gpt-4o-mini",
    structured_output={"schema": User},
    api_key="..."
)
llm.load()

result = llm.generate(
    [[{"role": "user", "content": "Create a user profile for the following marathon"}]],
    max_new_tokens=256
)

data = json.loads(result[0][0])
# data
# {'name': 'Marathon', 'last_name': 'Runner', 'id': 1}
```

**Comment by javimosa** [comment]
Yes, using the development version worked. Gracias @plaguss !
