### ISSUE TITLE
[BUG] OepnAI JSON format

### ISSUE THREAD

**Issue by tinyrolls** [argilla-io/distilabel#1048]
**Describe the bug**
The JSON response format's input structure for OpenAI's API appears to have changed to { "type": "json_object" }, causing compatibility issues with existing implementations.

**To Reproduce**
Code to reproduce
```python
pipeline.run(
    parameters={
        "task_with_openai": {
            "llm": {
                "generation_kwargs": {
                    "response_format": "json"
                }
            }
        }
    }
)
```

**Expected behaviour**
` openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid type for 'response_format': expected an object,
                             but got a string instead.", 'type': 'invalid_request_error', 'param': 'response_format', 'code': 'invalid_type'}}`

**Additional context
it should be `kwargs["response_format"] = {"type": response_format}`
 https://github.com/argilla-io/distilabel/blob/844165f25c1674076a8286d54cfe96d52c33a24e/src/distilabel/llms/openai.py#L304

**Comment by plaguss** [comment]
Hi @tinyrolls, thanks for noticing, this PR should fix it: #1053
