### ISSUE TITLE
[BUG] vLLM Task not utilizing multiple GPUs in parallel when replicas > 1

### ISSUE THREAD

**Issue by adamlin120** [argilla-io/distilabel#1049]
**Describe the bug**
When using multiple replicas for LLM generation in a Pipeline, the batches are being processed sequentially across GPUs instead of in parallel. For example, with 2 replicas, the entire first batch is processed on GPU1 before the second batch starts on GPU2, defeating the purpose of having multiple replicas.

**To Reproduce**
Code to reproduce
```python
from distilabel.pipeline import Pipeline
from distilabel.steps import LoadDataFromHub
from distilabel.steps.tasks import TextGeneration
from distilabel.llms.vllm import vLLM

with Pipeline(name="rejection-sampling") as pipeline:
    load_data_from_hub = LoadDataFromHub()
    text_generation = TextGeneration(
        llm=vLLM(
            model="meta-llama/Llama-2-7b-hf",
            tokenizer="meta-llama/Llama-2-7b-hf",
        ),
        input_batch_size=1000,
        num_generations=8,
        group_generations=True,
    )
    load_data_from_hub >> text_generation

distiset = pipeline.run(
    parameters={
        load_data_from_hub.name: {
            "repo_id": "yentinglin/metamath-qwen2-math-alpaca",
            "split": "train",
        },
        text_generation.name: {
            "llm": {
                "generation_kwargs": {
                    "temperature": 1.0,
                    "max_new_tokens": 4096,
                }
            },
            "resources": {"replicas": 2, "gpus": 1},
        },
    },
)
```

**Expected behaviour**
- With `replicas: 2`, batches should be distributed and processed in parallel across both GPUs
- Both GPUs should be actively processing different batches simultaneously

**Current Behavior**
- Batches are processed sequentially
- First batch completes on GPU1 before the second batch starts on GPU2
- No parallel processing despite multiple replicas being specified

**Screenshots**
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/e5e3d371-f43b-4ff7-b069-ff458cec0350">

**Desktop (please complete the following information):**
 - Package version: 1.4.1
 - Python version: 3.12.4

**Comment by gabrielmbmb** [comment]
Hi @adamlin120, this is happening because the `LoadDataFromHub` is yielding batches with the default size of `50` elements. Once `distilabel` gets 1000 elements i.e. 20 batches from `LoadDataFromHub` it will send the batch with the 1000 elements to one replica of `TextGeneration` and not until this batch is finished being processed new batches won't requested to the `LoadDataFromHub`, therefore one replica stays idle.

Updating the `LoadDataFromHub.batch_size` to a value like 2000 or 4000 should fix the issue:

```
load_data_from_hub = LoadDataFromHub(batch_size=2000)
```
