### ISSUE TITLE
[DOCS] Developer documentation guide

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/distilabel#132]
## Which page or section is this issue related to?

Adding a developer documentation guide, like https://docs.argilla.io/en/latest/community/developer_docs.html. Shall we also add an environment like in Argilla? @plaguss @alvarobartt @gabrielmbmb

**Comment by alvarobartt** [comment]
Hi here! So lets keep it simple for the moment, we can maybe add a short block within the docs to explain how to use `hatch` and how to install all the extras required to run the tests etc. but I think there's no need of something more complex than that 👍🏻 Happy to review if you do so!
