### ISSUE TITLE
[DOCS] Include CONTRIBUTING.md, CITATION.cff, CODE_OF_CONDUCT.md  and MANIFEST.in

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/distilabel#133]
## Which page or section is this issue related to?

Like Argilla's. Do you know any other that can be useful?

**Comment by alvarobartt** [comment]
Hey sounds nice, but lets not add too much complexity at this stage, because we want to iterate quickly and not introduce too many boilerplate 👍🏻

Also `CONTRIBUTING.md` is duplicated in the title, but lets add it!

**Comment by ignacioct** [comment]
> Hey sounds nice, but lets not add too much complexity at this stage, because we want to iterate quickly and not introduce too many boilerplate 👍🏻
> 
> Also `CONTRIBUTING.md` is duplicated in the title, but lets add it!

Gotcha @alvarobartt . Should I add a simple version of each?

**Comment by alvarobartt** [comment]
> > Hey sounds nice, but lets not add too much complexity at this stage, because we want to iterate quickly and not introduce too many boilerplate 👍🏻
> > Also `CONTRIBUTING.md` is duplicated in the title, but lets add it!
> 
> Gotcha @alvarobartt . Should I add a simple version of each?

Sorry, forgot to reply! Yes, please go ahead, I'll happily review those afterwards 👍🏻

**Comment by ignacioct** [comment]
> > > Hey sounds nice, but lets not add too much complexity at this stage, because we want to iterate quickly and not introduce too many boilerplate 👍🏻
> > > Also `CONTRIBUTING.md` is duplicated in the title, but lets add it!
> > 
> > 
> > Gotcha @alvarobartt . Should I add a simple version of each?
> 
> Sorry, forgot to reply! Yes, please go ahead, I'll happily review those afterwards 👍🏻

Yes! We have it on mind, but low prior right now
