### ISSUE TITLE
[DOCS] tutorial on using Notus for preference and instruction generation

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/distilabel#143]
## Which page or section is this issue related to?

Create a notebook for making a distilabel End-to-end example with Inference Endpoints and Notus, creating an Instruction and a Preference dataset, which can be shared as tutorial, blog post and dev content. https://www.notion.so/argilla/End-to-end-distilabel-example-with-Inference-Endpoints-and-Notus-4a1582a24e394166b477df91a298127a?pvs=4

**Comment by dvsrepo** [comment]
Hi! Good job! The workflow is good but we should use a more meaningful example, like reasoning or code or finance. Problems that are actually important for users, difficult for llms, and show the potential of building your own datasets for LLM fine-tuning. In general we should avoid toy examples
