### ISSUE TITLE
Can labeler use TransformersLLM?

### ISSUE THREAD

**Issue by ScottishFold007** [argilla-io/distilabel#191]
Can labeler use TransformersLLM?
Just like
```
instruction_task = SelfInstructTask(
        application_description="问题解答助手，可提供引人入胜、具有挑战性的数学测验和问题。"
    )
instruction_generator= TransformersLLM(
            model=model,
            tokenizer=tokenizer,
            task=instruction_task,
            max_new_tokens= 4096,
            temperature=0.83,
            prompt_format="chatglm",
            do_sample=True,
        )
pipeline = Pipeline(generator=instruction_generator)

distiset = pipeline.generate(dataset= raw_dataset.select([0]), num_generations=1, batch_size=1)

```

**Comment by gabrielmbmb** [comment]
Hi @ScottishFold007, yes, you can use the `TransformersLLM` also as a `labeller` in a `Pipeline`. Check out this example: https://github.com/argilla-io/distilabel/blob/main/examples/pipeline-prometheus.py

**Comment by dvsrepo** [comment]
Hi! Be aware that if you don't use a powerful enough model you won't get any results from the labelling process.

Prometheus and UltraCM are both open source and should do the job as Critiques models.

What type of dataset are you trying to build? In case we can help to guide you.
