### ISSUE TITLE
[FEATURE] ETA for time until completion for progress bars 

### ISSUE THREAD

**Issue by davanstrien** [argilla-io/distilabel#243]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an ETA for completion of the task when calling `pipeline. generate`.

**Describe the solution you'd like**
 At the moment, the progress bar gives an indication of progress, but it would be nice to also have an ETA of the time remaining. 

**Describe alternatives you've considered**
Being more patient... 

**Additional context**
I took a quick look, and since you are defining your own progress bar with Rich this might not be that easy to add.

**Comment by davidberenstein1957** [comment]
This might be interesting to check. https://timothygebhard.de/posts/richer-progress-bars-for-rich/

**Comment by davidberenstein1957** [comment]
@ignacioct, I believe we also show the "Row labelled" progress bar even if we don't use a labeller so you can fix that within this issue too.
