### ISSUE TITLE
[FEATURE] Add more flexibilty in construction of the SelfInstructTask template 

### ISSUE THREAD

**Issue by davanstrien** [argilla-io/distilabel#255]
**Is your feature request related to a problem? Please describe.**
When using Distilabel recently, I wanted to modify the ` # Criteria for Queries` part of the task template. Since this isn't currently exposed via the `SelfInstructTask` constructor I ended up patching  [self-instruct.jinja2](https://github.com/argilla-io/distilabel/blob/main/src/distilabel/tasks/_templates/self-instruct.jinja2) directly. 

**Describe the solution you'd like**
It might be nice to also expose this part of the template for the user to modify? 

**Describe alternatives you've considered**
At some point, the tasks might be modified so that they don't have much similarity to the original paper. I don't think this is such a problem but another possible approach would be to to add more functionality or documentation for constructing custom tasks.

**Comment by davidberenstein1957** [comment]
@davanstrien, we will wait for @alvarobartt and @gabrielmbmb to return from holidays to discuss the more structural change. For now, we will add some documentation to provide this overview. 
https://github.com/argilla-io/distilabel/issues/256
