### ISSUE TITLE
[DOCS] Document `prompt_formatting_fn` properly or remove from the codebase

### ISSUE THREAD

**Issue by plaguss** [argilla-io/distilabel#268]
## Which page or section is this issue related to?

The use of the argument [`prompt_formatting_fn`](https://github.com/argilla-io/distilabel/blob/main/src/distilabel/llm/base.py#L56) of the `LLM` is not well documented. If it's still has a fit we should document it properly and add some examples, otherwise we could remove it.

**Comment by alvarobartt** [comment]
Indeed I think all these questions will arise whenever we decide to go ahead with the configuration based runs, as some args may not be used or some others may be missing.

But yes, we should carefully review those and keep only what's used / usable.
