### ISSUE TITLE
[BUG] prepare_dataset fails when len generations != rating

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#280]
The prepare_dataset method is awesome @plaguss 

there's one edge case I found with a nasty preference dataset, sometimes we dont get all ratings, to fix it from my side I did:

filter(...len(r["generations"])==len(r["rating"])

It might make sense to check for this case and skip the example

No rush, I'll give you a dataset for testing, once is released with the world :-D

**Comment by dvsrepo** [comment]
haha I realise you can access it, it's the new dpo dataset I told you

**Comment by plaguss** [comment]
nice! will solve it next week.
