### ISSUE TITLE
[DOCS] add clarification in distilabel vLLM reference to specify dtype

### ISSUE THREAD

**Issue by kcentric** [argilla-io/distilabel#326]
## Which page or section is this issue related to?

Currently the code snippet in the vLLM section of the guide (https://distilabel.argilla.io/latest/technical-reference/llms/#vllm) looks like:

```python
llm = vLLM(
    model=LLM(model="argilla/notus-7b-v1"),
    task=TextGenerationTask(),
...
```

Running this as-is in a [Colab](https://colab.research.google.com/drive/1iPjuHhvMxe7LjDwZOzDJnXBWSpJ2ybhL?usp=sharing) notebook will result in "ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla T4 GPU has compute capability 7.5." This is discussed in [vLLM issues here](https://github.com/vllm-project/vllm/pull/1901).

Because everyone who uses Colab would likely use the T4 GPU (if they're on the free Colab at least), they'd face the same error every time if they copy our snippet from the Docs and try to test-run vLLM in their notebook.

I'd want to change the snippet to something like this:

```python
llm = vLLM(
    model=LLM(model="argilla/notus-7b-v1", dtype="Bfloat16"),  # If using Tesla T4 on Colab, 
                                                      # specify dtype = float16 to prevent compute compatibility error
    task=TextGenerationTask(),
```
and add a brief clarification about it in the text with a link for anyone who wants to understand it further.

**Comment by davidberenstein1957** [comment]
Hi @kcentric , feel free to create a PR for this.
