### ISSUE TITLE
[FEATURE] Allow json response specification from OpenAILLM

### ISSUE THREAD

**Issue by burtenshaw** [argilla-io/distilabel#328]
**Is your feature request related to a problem? Please describe.**
It would be useful when building datasets of JSON objects to use OpenAI's predefines JSON response parameter in [the API call](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format).

**Describe the solution you'd like**
Ideally, the OpenAILLM class could be instantiated with a specified response format that could be set to "json". The `__init__` could then represent that in the API request. see below

```python 
# interface
OpenAILLM(
    task=FunctionGeneratorTask(),
    num_threads=1,
    max_new_tokens=1024,
    model="gpt-3.5-turbo-1106",
    response_format="json"
)

# somewhere in init
self.response_format = {"type": "json_object"}

# in `def _generate()`
chat_completions = self.client.chat.completions.create(
    messages=prompt,
    model=self.model,
    n=num_generations,
    max_tokens=self.max_tokens,
    frequency_penalty=self.frequency_penalty,
    presence_penalty=self.presence_penalty,
    temperature=self.temperature,
    top_p=self.top_p,
    timeout=50,
    response_format=self.response_format,
)
```

**Describe alternatives you've considered**
I used a custom class and re-implemented the `_generate` method:

```python
class JSONOpenAILLM(OpenAILLM):
    def _generate(
        self,
        inputs: List[Dict[str, Any]],
        num_generations: int = 1,
    ) -> List[List[LLMOutput]]:
     ...
```

**Additional context**
N.B. this feature requires a limited list of models:
"An object specifying the format that the model must output. Compatible with [GPT-4 Turbo](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106."

We may wish to catch erroneous requests for models that do not support JSON responses. :thinking:

**Comment by plaguss** [comment]
Hi @burtenshaw, that would be a nice addition! Personally I think it would be easier to maintain if we go with your option for `JSONOpenAILLM`, and overwrite the appropriate methods (for example the `available_models` you mention there too, as this seem a specific feature for some of the models). But if you think it's better the first approach, totally fine. What do you think @alvarobartt, @gabrielmbmb, @davidberenstein1957 ?

**Comment by burtenshaw** [comment]
@plaguss Sounds good. If I go with `JSONOpenAILLM` I'll need to either introduce `response_format="text"` to `OpenAILLM` or reimplemt `_generate`.
