### ISSUE TITLE
Loading from disk

### ISSUE THREAD

**Issue by cmcmaster1** [argilla-io/distilabel#340]
https://github.com/argilla-io/distilabel/blob/a701e838c9aa7809d6674a815a9376c64e451590/src/distilabel/utils/serialization.py#L57

Am I stupid or are we trying to do division on two strings?

**Comment by cmcmaster1** [comment]
Change to a path join?

```python
os.path.join(path, TASK_FILE_NAME )
```

**Comment by dvsrepo** [comment]
hey! thanks, the function expects a `Path` object from pathlib. 

It's not a division. In this context, the / operator is used by the pathlib module to join paths, so path / TASK_FILE_NAME combines them into a full file path.

Are you passing a Path object?

cc @plaguss

**Comment by cmcmaster1** [comment]
Oh, I'm not. I assumed it behaved like the datasets "load_from_disk" method and I'm just giving a string. I admit, I didn't read the docs super carefully and can see the "PathLike" type now, but it also says "Path to the dataset, as you would do with a standard Dataset" which isn't quite true.

**Comment by dvsrepo** [comment]
> Change to a path join?
> 
> ```python
> os.path.join(path, TASK_FILE_NAME)
> ```

Yes I fully agree with should accept a string, thanks for the heads up! We'll consider it!

**Comment by dvsrepo** [comment]
> Oh, I'm not. I assumed it behaved like the datasets "load_from_disk" method and I'm just giving a string. I admit, I didn't read the docs super carefully and can see the "PathLike" type now, but it also says "Path to the dataset, as you would do with a standard Dataset" which isn't quite true.

Yes I fully agree with should accept a string, thanks for the heads up! We'll consider it!

**Comment by plaguss** [comment]
Hi @cmcmaster1, will try to clarify the function, thanks!
