### ISSUE TITLE
Create `CTRL + C` signal handler for gracefully pipeline stopping

### ISSUE THREAD

**Issue by gabrielmbmb** [argilla-io/distilabel#404]
Create a signal handler that captures `SIGINT` (ctrl + c) and stops the pipeline gracefully.

**Comment by bjoernpl** [comment]
This consistently stops me from being able to stop the execution of a pipeline if or when it got stuck somewhere. Would probably be best to have some override like exiting if crtl+c was pressed more than once or twice.

**Comment by alvarobartt** [comment]
To reproduce this @plaguss you can just create an infinite running step as:

```python
import time
from distilabel.steps import StepInput, step
from distilabel.steps.typing import StepOutput


@step()
def InfiniteStep(*inputs: StepInput) -> StepOutput:
    time.sleep(100)
```

And the CTRL+C will be captured, but the SIGTERM signal won't be sent.

**Comment by plaguss** [comment]
Hi @bjoernpl in the next release this should be tackled: https://github.com/argilla-io/distilabel/pull/630
