### ISSUE TITLE
[BUG] `UltraFeedbackTask` seems to *require* positional arguments

### ISSUE THREAD

**Issue by kcentric** [argilla-io/distilabel#468]
Hey, I think I've encountered a bug in `UltraFeedbackTask`, where the code claims that `ratings` and `task_description` are optional arguments, but when I try to initialize it in a Pipeline, I get an error saying "missing one positional argument".

Here's what the code in UltraFeedback looks like:

```python
class UltraFeedbackTask(PreferenceTask):
    """A `PreferenceTask` following the prompt template used by ULTRAFEEDBACK.

    Args:
        system_prompt (str, optional): the system prompt to be used for generation. Defaults to `None`.
        task_description (Union[str, None], optional): the description of the task. Defaults to `None`.
        ratings (Union[List[Rating], None], optional): the ratings to be used for the task. Defaults to `None`.

    References:
        - [`UltraFeedback: Boosting Language Models with High-quality Feedback`](https://arxiv.org/abs/2310.01377)
        - [`UltraFeedback - GitHub Repository`](https://github.com/OpenBMB/UltraFeedback)
    """

    ratings: List[Rating]
    task_description: str

    system_prompt: (
        str
    ) = "Your role is to evaluate text quality based on given criteria."
```

It seems like there's no "None" default set. 

What my pipeline looks like:

```python
preference_pipeline = pipeline(
    "preference",
    "instruction-following",
    labeller=GroqLLM(
        model="mixtral-8x7b-32768",  # type: ignore
        api_key=os.getenv("Groq_API_KEY"),
        task=UltraFeedbackTask(),
        max_new_tokens=256,
        num_threads=2,
        temperature=0.3,
    ),
```
The pipeline won't initialize because UltraFeedbackTask is requiring two positional arguments. 

If this seems like a valid case, I'll open a PR for it. Currently trying to work around it by mimicking the default pipeline setup in `pipeline.py` where you use `UltraFeedbackTask.for_overall_quality()` instead of just `UltraFeedbackTask` as the `task` argument.

**Comment by plaguss** [comment]
Hi @kcentric, sorry for the docstring misinformation, but in fact `ratings` and `task_description` are required, as they don't have a default value. There is no default task for `UltraFeedbackTask`, there are a different set of aspects that can be chosen depending on the task at hand, and those can be accessed through the different `classmethods` (the typical use would be to call for example `UltraFeedbackTask.for_helpfulness()`). If you want to create your own variant of an `UltraFeedbackTask`, you have the freedom by defining those arguments. You can find more information in the docs [here](https://distilabel.argilla.io/latest/technical-reference/tasks/#ultrafeedbacktask), where both `task_description` and `ratings` are defined.

**Comment by kcentric** [comment]
Thanks @plaguss! Yes, that makes sense. We could just update the docstring then I guess
