### ISSUE TITLE
[FEATURE] Add option to print or store each generation during a `pipeline` run

### ISSUE THREAD

**Issue by kcentric** [argilla-io/distilabel#469]
Related with #462.

**Description**
I've had several runs of a preference `pipeline` fail today, and essentially lost about $2 because I was using OpenAI GPT-4 to generate responses and on the 30th batch the `pipeline` stopped (hit my usage limit).

Now, I lost all those 30 batches of generations totally, because there was no automated saving or printing going on when the `pipeline` was running.

**Solution proposed**
Add some functionality in `pipeline.py` - possibly a parameter that allows you to store the generations "in-state" in a `.json` file. For example, I could have something like `preserve_state=True`, and then after every generation the pipeline creates or opens an existing JSON file. If the JSON file exists and there's already some generations up till now stored in there, it reads that into a list of dictionaries, updates the list with the new generation, and writes this updated list back to the JSON file.

This way, if someone wants to kill their process - such as if in my case I had 251 batches and just 29 of those cost of $2 with OpenAI, so I didn't to proceed further! Then you have all your generations up till now beautifully stored in a default JSON.

**Comment by dvsrepo** [comment]
Hi!

We should make more clear that users need to use this:

https://distilabel.argilla.io/latest/technical-reference/pipeline/#dataset-checkpoints

**Comment by kcentric** [comment]
Ah! Yes, I did see that argument was available, but I didn't know what exactly it was for. That would be helpful. 

Might it be possible it add a default value for `dataset-checkpoints`, just in case users don't use it?

**Comment by plaguss** [comment]
Hi @kcentric the default for the value is to have a `DatasetCheckpoint` with the default values as can be seen [here](https://distilabel.argilla.io/latest/reference/distilabel/pipeline/#distilabel.pipeline.Pipeline.generate) in the API reference, which results in the dataset being returned at the end of the pipeline by default. The reason for this was that we couldn't set a "sensible" value for the checkpointing (for example, we can set the checkpoint strategy to save the dataset every 100 records always, but that number implies a different frequency for a dataset of 100, 1K or 10K records for example, and for a bigger dataset, the default could mean that the dataset is saved to often, which could also be undesired). Thanks for your feedback, will try to improve the default behaviour.

**Comment by k-neev** [comment]
No worries, thanks @plaguss. Maybe we could make the argument a required one (but that could add some more complication) or set it to updating every 1/10th of whatever dataset size we have (which might have its own implications but personally for me it's better to save more frequently than less frequently 😅). Anyways, I see now.
