### ISSUE TITLE
[FEATURE] Add "smarter" parsing in `Pipeline`? 

### ISSUE THREAD

**Issue by kcentric** [argilla-io/distilabel#470]
Sometimes, when using `Pipeline` for a preference generation task, the labeling LLM doesn't obey instructions (even though I'm using Mixtral Instruct right now). Instead of giving it's rating just as "5.0" or "4.0", it goes "5.0 (Excellent)". Though it's kind of cute, it leads to a parsing error as in the screenshot below (I was using `TogetherInferenceLLM`). 

<img width="1110" alt="Screenshot 2024-03-24 at 1 41 17 PM" src="https://github.com/argilla-io/distilabel/assets/121068842/d493dc70-208f-4044-853f-445a0c660ed6">

So we could possibly add some kind of regex-aware parsing to fix this. Because the number 5 _is_ after all a part of that response the LLM gave, we could just pick out the number and cut off the rest of the string before converting it to float.

🤔 (Could be linked with #469 and #462 in a `Pipeline` update)

**Comment by alvarobartt** [comment]
Hi @kcentric, indeed we're almost done with our refactor in the `core-refactor` branch, and some of these issues are already fixed, the new version will be neat, and most of the things are improved, also thanks to user feedback like yours! 🤗 Looking forward to releasing and sharing with you! cc @gabrielmbmb @plaguss
