### ISSUE TITLE
[BUG]  `InferenceEndpointsLLM` breaks with the `0.22.1` release of the `huggingface_hub` library. 

### ISSUE THREAD

**Issue by davanstrien** [argilla-io/distilabel#484]
**Describe the bug**
The `InferenceEndpointsLLM` seems to break with the `0.22.1` release of the `huggingface_hub` library. Likely the private module `huggingface_hub.inference._text_generation` was moved.

**To Reproduce**
Code to reproduce
```python
from distilabel.llm import InferenceEndpointsLLM
```
Results in 

```
ModuleNotFoundError: No module named 'huggingface_hub.inference._text_generation'
```

A temporary fix would be to pin the library i.e. `huggingface_hub<=0.21.0`. I didn't have a chance to dig into this in much detail but probably the fix isn't too complicated. 

cc @Wauplin

**Comment by Wauplin** [comment]
Sorry about that :see_no_evil: Opened a PR to fix it: https://github.com/argilla-io/distilabel/pull/485
