### ISSUE TITLE
[DOCS] Typo in Docs

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [argilla-io/distilabel#536]
## Which page or section is this issue related to?

https://distilabel.argilla.io/0.6.0/tutorials/pipeline-notus-instructions-preferences-legal/#generating-instructions-with-selfinstructtask

## What are you documenting, or what change are you making in the documentation?

The first sentence should begin with "With our Inference Endpoint up and running", not with "With out Inference Endpoint...".

**Comment by DamianB-BitFlipper** [comment]
Additional typo further down: "The pipeline has succesfully generated instructions given the topics and the behaviour passed as input. Let's gather all those instructions and see how the look." -> "The pipeline has succesfully generated instructions given the topics and the behaviour passed as input. Let's gather all those instructions and see how **they** look."

**Comment by gabrielmbmb** [comment]
Hi @DamianB-BitFlipper, thanks for creating the issue!

We're soon releasing distilabel `1.0.0` which comes with new docs and we haven't included this tutorial. Anyways, if we update the tutorial for the `1.0.0`, we will have this in mind.

Thanks!
