### ISSUE TITLE
[FEATURE] Infer the name of the step instead of asking the user

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#572]
**Is your feature request related to a problem? Please describe.**

As part of my initial analysis to improve the dev experience, would it be possible to infer/assign the name of the step if they user doesn't provide one. 

I understand it might not be straightforward and it's a nice-to-have suggestion, so feel free to close this if too much burden.

```python
    # do
    generate_with_llama3 = TextGeneration(
        llm=InferenceEndpointsLLM(
            model_id="meta-llama/Meta-Llama-3-70B-Instruct",
            tokenizer_id="meta-llama/Meta-Llama-3-70B-Instruct",
            api_key=userdata.get('HF_TOKEN')
        ),
    )
   # instead of
    generate_with_llama3 = TextGeneration(
        name="generate_with_llama3",
        llm=InferenceEndpointsLLM(
            model_id="meta-llama/Meta-Llama-3-70B-Instruct",
            tokenizer_id="meta-llama/Meta-Llama-3-70B-Instruct",
            api_key=userdata.get('HF_TOKEN')
        ),
    )
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gabrielmbmb** [comment]
Hi @dvsrepo! The main reason `name` was not optional and not automatically generated is because you need to know the name of the step to provide runtime parameters.

We can automatically generate the name if not provided, but it the user needs to provide a runtime parameter for that step, then it can be confusing.

**Comment by dvsrepo** [comment]
ok, it's fine, not worth the burden then, we can close this for now
