### ISSUE TITLE
[FEATURE] Include custom steps, requirements in pipeline config file and `allow_remote_code` flag

### ISSUE THREAD

**Issue by gabrielmbmb** [argilla-io/distilabel#573]
## Description

Currently, the pipelines that can be executed directly from the CLI or when loaded with `Pipeline.from_yaml` are those which include only steps from `distilabel` package.

The idea is to also serialize custom steps (as safe as possible) and include them in the pipeline config file, so if an user desires to execute the pipeline from the CLI, it can be executed if `allow_remote_code=True`.

In addition, some pipelines requires some dependencies to be executed (`transformers`, `openai`, etc). These requirements should be also added to the pipeline config file and when executing from CLI and if not installed, then prompt the user to consent the install of these requirements.

**Comment by plaguss** [comment]
As internally discussed, we will include the requirements of the pipeline, as well as the option of pushing the pipeline to the repository when calling `distiset.push_to_hub`, but won't implement this due to the complexity and benefit we would obtain from it
