### ISSUE TITLE
[FEATURE] Enable debugging cols similar to the previous raw_generation and labelling_prompt

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#582]
**Is your feature request related to a problem? Please describe.**

I'm testing a preference pipeline with Llama3 and the parsed outputs are weird (long lists of ratings and rationales when my number of generations is two). I'd like to have a way to automatically enable some columns in my resulting distiset to inspect:

1. The prompt sent by the UltraFeedback task
2. The raw responses parsed with the UF task

This is of course applicable to other Steps but it's more crucial when using tasks with complex prompt templates and output parsing.

**Describe the solution you'd like**
Something like enable debug columns when I setup the Task

**Describe alternatives you've considered**
Please suggest alternatives I can use in the meantime

**Additional context**

**Comment by plaguss** [comment]
From now on, we can decide deal with this like in the [example](https://github.com/argilla-io/distilabel/pull/586#issuecomment-2104325256). Will update the docs accordingly!

**Comment by dvsrepo** [comment]
> From now on, we can decide deal with this like in the [example](https://github.com/argilla-io/distilabel/pull/586#issuecomment-2104325256). Will update the docs accordingly!
this looks awesome!
