### ISSUE TITLE
[BUG] Branching can misalign rows if a batch on a branch fails

### ISSUE THREAD

**Issue by bjoernpl** [argilla-io/distilabel#587]
**Describe the bug**
When branching in a pipeline (for example to process something with multiple llms) and merging the branches back together (`["generation", "model"], ["generation", "model"] -> ["generation_a", "generation_b", "model_a", "model_b"]`) it can happen that the batches getting sent to the merge step are misaligned. If one batch fails when branched (if an LLM call fails for example), then the failed batch will "disappear" instead of returning Nones. Imagine batch 3 fails for task b, then it gets skipped and when merging results, batch 3 of task a gets merged with batch 4 of task b. This behaviour also leads to the pipeline not completing (but also not failing) I guess since there are still batches from a but none left from b.

**To Reproduce**
I couldn't reproduce this consistently since the API calls would fail at random and I didn't know how to mock this. If you have some setup where you can test what happens when an llm call fails, you should be able to reproduce this.
```python
# This is pseudocode to show the general setup

@step(inputs=["translation", "model_name"], outputs=["translation_a", "translation_b"])
def GatherTranslations(*input_batches: StepInput) -> "StepOutput":
    batches_a, batches_b = input_batches
    for i, batch_a in enumerate(batches_a):
        batch_b = batches_b[i]
        batch_a["translation_a"] = batch_a["translation"]
        batch_a["translation_b"] = batch_b["translation"]
        del batch_a["translation"]
        del batch_a["model_name"]
    yield batches_a

gather_translations = GatherTranslations(name="gather_translations")
# if any batch of either of these fail, the resulting dataset will be reduced in length and will be misaligned
translate_a = Translate(llm=OpenAILLM(model="gpt-4-turbo"), name="translate_a")
translate_b = Translate(llm=OpenAILLM(model="gpt-4-0613"), name="translate_b")

load_hub_dataset.connect(translate_a)
load_hub_dataset.connect(translate_b)
translate_a.connect(gather_translations)
translate_b.connect(gather_translations)
```

**Expected behaviour**
I would expect the order to remain intact even if errors occur and for the missing values to get filled with Nones.

**Screenshots**
<img width="701" alt="image" src="https://github.com/argilla-io/distilabel/assets/32109055/b07c9106-e701-4778-9602-5357c1fecbad">
See this example where this occured and translation b is for an entirely different document than translation a

**Desktop (please complete the following information):**
 - Package version: Installed from source at https://github.com/argilla-io/distilabel/commit/9f38b4931398f626e07cbe2a83ef393de661f428
 - Python version: 3.11

**Additional context**

**Comment by gabrielmbmb** [comment]
We just merged a fix in `develop`. Will be released in `1.1.0`, with other changes related to the manage of the batches. Thanks for reporting!
