### ISSUE TITLE
[BUG] `dry_run` require parameters

### ISSUE THREAD

**Issue by sdiazlor** [argilla-io/distilabel#653]
**Describe the bug**
If I'm not wrong I can `pipeline.dry_run` without any parameter as in `pipeline.run`. However, this is not allowed.

**To Reproduce**
Code to reproduce
```python
with Pipeline(name="mistral-pipe", description="A pipeline to generate and score a distiset") as pipeline:

    load_dataset = LoadDataFromDicts(
        name= "load_dataset", data=[{"input": "test"}],
    )
distiset = pipeline.dry_run()
```

**Expected behaviour**

**Screenshots**
![image](https://github.com/argilla-io/distilabel/assets/127759186/9758e273-2ff8-4a0d-ba75-b114401954ac)
![image](https://github.com/argilla-io/distilabel/assets/127759186/2f1865d7-713c-439d-ab7b-facd8c585b32)
![image](https://github.com/argilla-io/distilabel/assets/127759186/c7a25b28-9c21-4dec-afa7-2c100dcbc0e6)

**Desktop (please complete the following information):**
 - Package version: 1.1.0
 - Python version: Python 3.10.12

**Additional context**

**Comment by plaguss** [comment]
Thanks for reporting @sdiazlor, will tackle this later today.
