### ISSUE TITLE
[CI] Install both `minimum` and `latest` dependencies in CI

### ISSUE THREAD

**Issue by alvarobartt** [argilla-io/distilabel#669]
## Description

In order to improve the robustness of the CI process and avoid conflicts with the dependencies, we should be running the CI with both the stated to be the minimum supported version for each dependency, as well as with the `latest` i.e. the only current approach.

## Approach

Ideally we can use https://github.com/astral-sh/uv, as it comes with a `--resolution` flag that will let us set `lowest` and `highest`.

See https://github.com/astral-sh/uv?tab=readme-ov-file#resolution-strategy

**Comment by gabrielmbmb** [comment]
I think we should be careful with the minimum required version that we put for our dependencies, and trust that new versions of our dependencies are backward compatible, otherwise, we will increase CI time.

**Comment by alvarobartt** [comment]
> I think we should be careful with the minimum required version that we put for our dependencies, and trust that new versions of our dependencies are backward compatible, otherwise, we will increase CI time.

Yes, that's why I wanted to bring this up, since the current minimum version of `datasets` is not compatible with our caching approach for `load_dataset`; and that would have been captured in the unit tests otherwise. Ideally this will only run on commits to `main` i.e. before releasing.
