### ISSUE TITLE
[FEATURE] Make `LoadHubDataset` more general to read local files

### ISSUE THREAD

**Issue by plaguss** [argilla-io/distilabel#687]
**Is your feature request related to a problem? Please describe.**
I created a custom step to read data from a jsonlines file in the local fileystem, but noted that `load_dataset` already has the functionality, we only need to expose it.

**Describe the solution you'd like**
Allow reading local files using `LoadHubDataset`, something similar to the following

```python
load_dataset = LoadHubDataset(
    filetype="json",
    filename="path/to/dataset.jsonl"
)
```

**Describe alternatives you've considered**
Creating a custom step when needed.

**Additional context**
Ref: https://huggingface.co/docs/datasets/loading#local-and-remote-files

**Comment by alvarobartt** [comment]
I also wanted to bring up the fact that we now have `LoadDataFromDicts` and `LoadHubDataset`; most of the times, myself, as an user, end up writing `LoadDataFromHub` assuming the standard is `LoadDataFrom ...`; maybe this is a nice time to unify everything under the same naming pattern? I believe this will be easier and avoid conflicts in the future (we can set a deprecation warning on `LoadHubDataset` for the next couple of releases to avoid breaking any existing pipeline).

**Comment by rasdani** [comment]
After the merge of #673 there also needs to be a `LoadS3Dataset` or not?

Like this:
https://github.com/argilla-io/distilabel/issues/665#issuecomment-2126578916

**Comment by plaguss** [comment]
Closing this with https://github.com/argilla-io/distilabel/pull/691. @rasdani will let you know once we add the docs, but the you could use the new `LoadDataFromDisk` to work with the s3 datasets saved to disk.
