### ISSUE TITLE
[DOCS] Update cite information

### ISSUE THREAD

**Issue by borgr** [argilla-io/distilabel#692]
## Which page or section is this issue related to?

README, the README should include some @misc{} citation so people in academia cite it.

**Comment by davidberenstein1957** [comment]
Hi @borgr, this has been added to the GitHub main repo through the CITATION.cff file. @alvarobartt perhaps we can add this during the next iteration of the docs too?

**Comment by davidberenstein1957** [comment]
I think we can update the cite info to "Argilla team", not to have to touch it when teams change, and we can add it explicitly to the readme too.
