### ISSUE TITLE
[FEATURE] review naming columns `Steps`: `CombineColumns`, `CombineKeys`, `ExpandColumns` 

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/distilabel#755]
**Is your feature request related to a problem? Please describe.**
The naming for these operations is a bit fragmented and not always as explicit/intuitive.

**Describe the solution you'd like**
I propose reviewing the naming and perhaps aligning it with a more familiar naming and API design like the one used in pandas.

- `ExpandColumns` is nice and explicit, but I think pandas uses explode, so something like `ExplodeColumns` would perhaps be better.
- `CombineKeys` uses the Keys in the name, but I think it would be better to go for something like `AggregateColumns`/ `MergeColumns`, `AppendColumns`  
- `CombineColumns` seems to groupby operation and not really a combination. Perhaps something like `GroupByColumns` might be better.

Open to iterating on the naming.

**Describe alternatives you've considered**
N.A.
**Additional context**
N.A.

**Comment by plaguss** [comment]
Hi! I think that can be useful too. 
- I think `CombineKeys` can be renamed to `MergeColumns` (this one would be the easiest, it's not released yet), it's more explicit, and it's really what it does.
For the other two, I'm not sure we should follow the same naming convention as pandas:
- `CombineColumns` I think it works fine with `GroupColumns`, not necessarily the `GroupBy`, the operation groups elements in a dictionary, but doesn't group elements in columns in the same sense of a pandas dataframe or a table.
- `ExpandColumns` given that is explicit as it is, there's no need to change it.
