### ISSUE TITLE
UltraFeedback error with TogetherAI

### ISSUE THREAD

**Issue by sameearif** [argilla-io/distilabel#763]
`ultrafeedback = UltraFeedback(
    name="ultrafeedback",
    llm=TogetherLLM(model="meta-llama/Llama-3-70b-chat-hf",
                    base_url="https://api.together.xyz/v1",
                    generation_kwargs= {"max_new_tokens": 512, "temperature": 0.7}),
    aspect="overall-rating",
    output_mappings={"model_name": "ultrafeedback_model"},
)`

`ultrafeedback.load()`

`result = next(
    ultrafeedback.process(
        [
            {
                "instruction": instruction
                "generations": [
                    out1,
                    out2
                ]
            }
        ]
    )
)`

Error: BadRequestError: Error code: 400 - {'error': {'message': 'json_object is the only supported response_format type', 
'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}

**Comment by gabrielmbmb** [comment]
@sameearif we've just released `1.2.1`, it should work now :)

**Comment by sameearif** [comment]
@gabrielmbmb Thank you so much for the fast response!
