### ISSUE TITLE
[FEATURE] Introduce Critique Task (UF, JudgeLM, Prometheus)

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#77]
The idea is to introduce a new task to add LLM-As-Judge / Critique models that assess a single response individually instead of a list of generations together.

Ideally, this should work for:

- `len(generations)=1`
- `len(generations)>1`: needs an architectural change? The idea is to pass several generations and run the critique over each generation individually.

Target models:

- UF (used by Zephyr train_prefs)
- JudgeLM 
- Prometheus: high potential as it would mean getting rid of GPT4 as labeller

**Comment by zucchini-nlp** [comment]
@davidberenstein1957 Hi, this seems interesting to me, I can work on it starting this week

**Comment by davidberenstein1957** [comment]
Hi @zucchini-nlp , that would be great. @alvarobartt @gabrielmbmb, could you provide help wherever needed?

**Comment by zucchini-nlp** [comment]
Hi @dvsrepo . Okay, thanks, I will start from that one then. One quick clarification, is there any specific LLM we want to use for benchmarking?

**Comment by alvarobartt** [comment]
We tend to recommend / default to OpenAI whenever it comes to labelling, as those seem to be the ones that behave the better (both `gpt-3.5-turbo` and `gpt-4`), even though we also may cook something internally, but for the moment, OpenAI is a nice starting point via the `OpenAILLM` class under `distilabel.llm.OpenAILLM`
