### ISSUE TITLE
[FEATURE] Create a direct way of passing a dataset as part of a pipeline

### ISSUE THREAD

**Issue by plaguss** [argilla-io/distilabel#779]
**Is your feature request related to a problem? Please describe.**
There are users that want to process a dataset on its own and just use it in a pipeline, without writing it to disk first, or uploading it to the Hugging Face Hub and download it afterwards. We have to offer this possibility.

**Describe the solution you'd like**
A simple way of passing a `datasets.Dataset` or `pandas.DataFrame` for example already loaded to a Pipeline.

**Describe alternatives you've considered**
Write it first to disk or upload it to the HF Hub.

**Additional context**

**Comment by dvsrepo** [comment]
For ref, this is how I work to iterate a sample of my data:

https://huggingface.co/blog/dvilasuero/synthetic-data-with-llama3-distilabel#load-dataset

```python
# get great prompts annotated by at least 2 contributors
dataset = load_dataset(
  "DIBT/10k_prompts_ranked",
  split="train"
).filter(
  lambda r: r['avg_rating']>=4 and r['num_responses']>=2
)

dataset = dataset.to_list()
load_dataset = LoadDataFromDicts(
  name="load_dataset",
  data=dataset[0:500], # during development I used [0:1] to iterate quickly
  output_mappings={"prompt": "instruction"}
)
```
