### ISSUE TITLE
[FEATURE] : Open AI Like Class for drop in configurations for clients

### ISSUE THREAD

**Issue by Josephrp** [argilla-io/distilabel#794]
### Issue OpenAI-like endpoints are prevalent

With three openai-like end points and huggingface recently moving to the same , it would "forward thinking" to make a openai-like llm class for these to use.

### Tasks

- [ ] Create OpenAI -like class 
- [ ] refactor openai-like-clients accordingly
  - [ ] TogetherAI
  - [ ] Anyscale
  - [ ] OneAI (01ai)
  - [ ] Huggingface (?)

### Solution

although there will be less clients overall it will be more elegant to include them in examples rather than in code.

**Comment by plaguss** [comment]
Hi @Josephrp, thanks for opening the issue. Could you elaborate a bit more what you expect from the codebase? We have an `OpenAILLM` class from which [`Anyscale`](https://github.com/argilla-io/distilabel/blob/main/src/distilabel/llms/anyscale.py) or [ `TogetherAI`](https://github.com/argilla-io/distilabel/blob/main/src/distilabel/llms/together.py) inherit already.

**Comment by plaguss** [comment]
Closing this, feel free to reopen if there is something to improve
