### ISSUE TITLE
[DOCS] Inconsistent variable names in pipeline example causing errors (in ultrafeedback.md)

### ISSUE THREAD

**Issue by Hassaan-Qaisar** [argilla-io/distilabel#798]
## Which page or section is this issue related to?
https://github.com/argilla-io/distilabel/blob/main/docs/sections/pipeline_samples/papers/ultrafeedback.md
https://distilabel.argilla.io/latest/sections/pipeline_samples/papers/ultrafeedback/#code

## What are you documenting, or what change are you making in the documentation?
In the provided code samples for the pipeline, there is an inconsistency in the variable names for the UltraFeedback step.
In the first code sample, the variable is named ultrafeedback
In the second code sample, the parameter used is ultrafeedback_openai
This discrepancy causes an error when running the pipeline, as the variable names do not match. To resolve this, the variable names should be consistent across both code samples.
![image](https://github.com/user-attachments/assets/e2068f69-b5e5-4514-8166-55bfdbd0467a)
![image](https://github.com/user-attachments/assets/8660db34-1be5-4682-a766-ba40cc13fb29)

**Comment by plaguss** [comment]
Thanks for the catch @Hassaan-Qaisar!
