### ISSUE TITLE
[FEATURE] add a functionality to visualise /draw `Pipelines` and `Steps`

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/distilabel#816]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be nice to be able to visualise a pipeline while building it.

**Describe alternatives you've considered**
Going in blind.

**Additional context**
https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_pipeline_display.html
https://docs.haystack.deepset.ai/docs/visualizing-pipelines

**Comment by davidberenstein1957** [comment]
Related to https://github.com/argilla-io/distilabel/issues/368

**Comment by plaguss** [comment]
Related to #835
