### ISSUE TITLE
ModuleNotFoundError: No module named 'distilabel.embeddings'

### ISSUE THREAD

**Issue by msamwelmollel** [argilla-io/distilabel#849]
I update the distilabel but still get the same error 

import json
from typing import TYPE_CHECKING, Any, Dict, List, Literal, Union

from distilabel.llms import vLLM
from distilabel.pipeline import Pipeline
from distilabel.embeddings import SentenceTransformerEmbeddings
from distilabel.steps import (
    step,
    StepInput,
    EmbeddingGeneration,
    FaissNearestNeighbour,
    RewardModelScore,
    ConversationTemplate,
)
from distilabel.steps.tasks import MagpieGenerator, Task, TextGeneration, ChatGeneration

**Comment by gabrielmbmb** [comment]
Hi @msamwelmollel! `SentenceTransformersembeddings` hasn't been released yet. If you want to use it you can install from git version `distilabel[sentence-transformers] @ git+https://github.com/argilla-io/distilabel.git@develop`.

**Comment by msamwelmollel** [comment]
> Hi @msamwelmollel! `SentenceTransformersembeddings` hasn't been released yet. If you want to use it you can install from git version `pip install distilabel[sentence-transformers] @ git+https://github.com/argilla-io/distilabel.git@develop`.

Thank it worked I used: pip install git+https://github.com/argilla-io/distilabel.git@develop
