### ISSUE TITLE
[DOCS] tutorial - generate data for training embeddings and reranking models

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/distilabel#890]
## Which page or section is this issue related to?

An addaptation of https://docs.zenml.io/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings-with-sentence-transformers

## What are you documenting, or what change are you making in the documentation?

NA

**Comment by gabrielmbmb** [comment]
Hi @davidberenstein1957 , we already have https://github.com/argilla-io/argilla-sdk-chatbot and https://github.com/argilla-io/argilla-sdk-chatbot/blob/main/train_embedding.ipynb, maybe we can add a reference.
