### ISSUE TITLE
how to use mistral api ?

### ISSUE THREAD

**Issue by CryptoMaN-Rahul** [argilla-io/distilabel#896]
just wanted to know how to use mistral api,, im a newbiw

**Comment by plaguss** [comment]
Hi @CryptoMaN-Rahul have you taken a look at the quickstart example in the docs: https://distilabel.argilla.io/latest/sections/getting_started/quickstart/?
The [`Tasks`](https://distilabel.argilla.io/latest/sections/how_to_guides/basic/task/) are agnostic to the [`LLM`](https://distilabel.argilla.io/latest/sections/how_to_guides/basic/llm/#working-with-llms) chosen.
In the API you can find the specific case of [`MistralLLM`](https://distilabel.argilla.io/latest/components-gallery/llms/mistralllm/), and also a specific pipeline example using `Mistral` to generate structured data: [MistralAI with instructor](https://distilabel.argilla.io/latest/sections/pipeline_samples/examples/#mistralai-with-instructor)

**Comment by plaguss** [comment]
The `MistralLLM` was updated to use the new client of version 1.0.0, if you install from the develop branch and test it, let us know if it works

**Comment by CryptoMaN-Rahul** [comment]
Sure , i will
