### ISSUE TITLE
[FEATURE] Update `MistralLLM` to use the client of version 1.0.0

### ISSUE THREAD

**Issue by plaguss** [argilla-io/distilabel#900]
**Is your feature request related to a problem? Please describe.**
Mistralai has updated the client and we should update the code to keep up to date.

**Describe the solution you'd like**
There's a guide for the migration process [here](https://github.com/mistralai/client-python/blob/main/MIGRATION.md),
we should update the async client internally.

**Describe alternatives you've considered**

**Additional context**

**Comment by gabrielmbmb** [comment]
Duplicate, closing in favour of https://github.com/argilla-io/distilabel/issues/884
