### ISSUE TITLE
How to load local hf dataset？

### ISSUE THREAD

**Issue by yuqie** [argilla-io/distilabel#909]
Hi, I have run the example provided on this [page](https://github.com/argilla-io/distilabel?tab=readme-ov-file#example) and it run well. Then I tried to load a local HF dataset and found that the class LoadDataFromDisk. 

I saved the dataset using the `save_to_disk` method like `dataset.save_to_disk(dataset_dict_path='./save_data') ` and following is the structure of the saved dataset directory.

save_data/
├── dataset_dict.json
└── test
    ├── data-00000-of-00001.arrow
    ├── dataset_info.json
    └── state.json

I only changed the "repo_id" to "dataset_path" (a local LLM is used). When I run the following code, a Value error encountered 
```
ValueError: Step 'load_data_from_disk_0' is missing required runtime parameter 'repo_id'. Please, provide a value for it when calling `Pipeline.run` method:

    pipeline.run(parameters={"load_data_from_disk_0": {"repo_id": ...}})
```

```
from distilabel.llms import vLLM
from distilabel.pipeline import Pipeline
from distilabel.steps import LoadDataFromDisk
from distilabel.steps.tasks import TextGeneration

with Pipeline(
    name="simple-text-generation-pipeline",
    description="A simple text generation pipeline",
) as pipeline:
    load_dataset = LoadDataFromDisk(output_mappings={"prompt": "instruction"})

    generate_with_openai = TextGeneration(llm=vLLM(model="/home/public_data/qwen/Qwen2-7B-Instruct/"))

    load_dataset >> generate_with_openai

if __name__ == "__main__":
    distiset = pipeline.run(
        parameters={
            load_dataset.name: {
                "dataset_path": "/home/qiey/DataGenration/save_data",
                "split": "test",
            },
            generate_with_openai.name: {
                "llm": {
                    "generation_kwargs": {
                        "temperature": 0.7,
                        "max_new_tokens": 512,
                    }
                }
            },
        },
    )

```
could anyone give me some advice, any suggestion is appreciated.

**Comment by gabrielmbmb** [comment]
Hi @yuqie! This is a bug that we had and that we have fixed https://github.com/argilla-io/distilabel/pull/898 you can try either installing `distilabel` from `develop` branch or simple pass the attribute `repo_id="random"` to by pass the issue until we release the next version.

**Comment by yuqie** [comment]
Hi @gabrielmbmb!,  thanks for your help. I have tried to pass "random" to repo_id, it works when I tried load the dataset alone.
```
from distilabel.steps import LoadDataFromDisk
load_dataset = LoadDataFromDisk(repo_id="random",dataset_path="/home/qiey/DataGenration/save_data",output_mappings={"prompt": "instruction"})
```
If I used it with the pipeline, a ValueError which required the parameter 'config' is encountered.
```
ValueError: Step 'load_data_from_disk_0' is missing required runtime parameter 'config'. Please, provide a value for it when calling `Pipeline.run` method:

    pipeline.run(parameters={"load_data_from_disk_0": {"config": ...}})

```
Here is the whole code.
```
from distilabel.llms import vLLM
from distilabel.pipeline import Pipeline
from distilabel.steps import LoadDataFromDisk
from distilabel.steps.tasks import TextGeneration

with Pipeline(
    name="simple-text-generation-pipeline",
    description="A simple text generation pipeline",
) as pipeline:
    load_dataset = LoadDataFromDisk(repo_id="random",dataset_path="/home/qiey/DataGenration/save_data",split="test",output_mappings={"prompt": "instruction"})

    generate_with_openai = TextGeneration(llm=vLLM(model="/home/public_data/qwen/Qwen2-7B-Instruct/"))

    load_dataset >> generate_with_openai

if __name__ == "__main__":
    distiset = pipeline.run(
        parameters={
            generate_with_openai.name: {
                "llm": {
                    "generation_kwargs": {
                        "temperature": 0.7,
                        "max_new_tokens": 512,
                    }
                }
            },
        },
    )
```
I tried to add the parameter config="default", the following is happened:
```
ValueError: Dataset not loaded yet, you must call `load` method first.
```
btw the distibabel version is 1.2.4, and I tried to update to 1.3.1. I run with the thread error no matter local data or hf dataset.
```
RuntimeError: Failed to load all the steps. Could not run pipeline.
Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
```

**Comment by plaguss** [comment]
Hi @yuqie, we are working to fix this bug in PR https://github.com/argilla-io/distilabel/pull/910.
Once it's merged, you should be able to use the class as expected. The `load` method will be done automatically if necessary, the config will be optional (it will default to `default`, which is the standard name, but if that's not possible, an error will be raised informing).

Related to the last `RuntimeError`, let's see after trying with the new version, and if that persists, maybe you can try running with the `dry_run` and sharing the full error trace

**Comment by plaguss** [comment]
Closing this, reopen it if you find the error persists, or open a new one if some other error appears 😄
