### ISSUE TITLE
[BUG] Table column mismatches if llm throws exception

### ISSUE THREAD

**Issue by zye1996** [argilla-io/distilabel#975]
**Describe the bug**
The problem happens, when this line throw an exception and add_raw_output is set to True: https://github.com/argilla-io/distilabel/blob/ed88585a0b60a785ec9a8010a2c69eab22394ca2/src/distilabel/steps/tasks/base.py#L198

When the exception is raise, "distilabel_metadata" is not able to added to the output, which causes this line fail: https://github.com/argilla-io/distilabel/blob/ed88585a0b60a785ec9a8010a2c69eab22394ca2/src/distilabel/pipeline/write_buffer.py#L135

If this happened, pipeline crached. I found that the pipeline hung when recovered from cache, which means cache is corrupted somewhere. 

I could submit a pull request but please advise what is the best way to address the issue. (I am currently add the empty output in impute_step_outputs as follows:)

```
    def _impute_step_outputs(self, batch: "_Batch") -> List[Dict[str, Any]]:
        """Imputes the step outputs columns with `None` in the batch data.

        Args:
            batch: The batch to impute.
        """
        result = []
        for row in batch.data[0]:
            data = row.copy()
            for output in self.step.outputs:
                data[output] = "N/A"
            if isinstance(self.step, Task):
                if self.step.add_raw_output or self.step.add_raw_input:
                    data[DISTILABEL_METADATA_KEY] = {}
            result.append(data)
        return result
```

Moreover, personally I think the following code could be safer:
```
if not last_schema.equals(table.schema):
    new_schema = pa.unify_schemas([last_schema, table.schema])
    self._buffer_last_schema[step_name] = new_schema
    table = table.cast(new_schema)
```

into something like, otherwise cast could fail even if schema are the same except the column order
```
if not last_schema.equals(table.schema):
    if set(last_schema.names) == set(table.schema.names):
        table = table.select(last_schema.names)
    else:
        new_schema = pa.unify_schemas([last_schema, table.schema])
        self._buffer_last_schema[step_name] = new_schema
        table = table.cast(new_schema)
```

**To Reproduce**
See above
```

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Package version:
 - Python version:

**Additional context**
Add any other context about the problem here.

**Comment by zye1996** [comment]
@gabrielmbmb do you think it is better to add interface of self.impute_step_outputs at step level?

**Comment by gabrielmbmb** [comment]
Hi @zye1996! Yes, I think it makes sense to have `impute_outputs` as a method in the `_Step` class. The other change for the schema creation looks good too!
